name: GCC

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true

jobs:
  linux:
  
    runs-on: ubuntu-20.04
    
    steps:
    
    - name: 签出源码
      uses: actions/checkout@v3
      
    - name: 安装依赖
      run: |
        sudo apt-get update && sudo apt-get install -yq libboost-all-dev g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
        
    - name: 配置项目
      run: |
        mkdir bin
        cd bin
        cmake ../ -DCMAKE_BUILD_TYPE=Release -DTOOLS=1 -DWITH_WARNINGS=1
        cd ..
        
    - name: 编译项目
      run: |
        cd bin
        make authserver
        make worldserver

    - name: 上传资源
      uses: actions/upload-artifact@v3
      with:
        name: server-linux-64x-v${{ github.event.inputs.tag_name }}
        path: ./bin/check_install/bin/**/*

  publish:
    runs-on: ubuntu-latest
    needs: [ linux ]
    steps:
    - name: 下载资源
      uses: actions/download-artifact@v3
      with:
        name: server-linux-64x-v${{ github.event.inputs.tag_name }}
        path: server-linux-64x-v${{ github.event.inputs.tag_name }}/

    - name: 打包资源
      run: |
        cd server-linux-64x-v${{ github.event.inputs.tag_name }}/ && tar cvfz ../server-linux-64x-v${{ github.event.inputs.tag_name }}.tgz ./ && cd -

    - name: 发布版本
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.tag_name }}
        name: server-v${{ github.event.inputs.tag_name }}
        body: v${{ github.event.inputs.tag_name }} 版本发布.
        draft: false
        prerelease: false
        files: |
          server-linux-64x-v${{ github.event.inputs.tag_name }}.tgz
